// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_BcKXYXUevKyewJyCrWGiyaGlACdi-Ak',
    appId: '1:902994248515:web:259158f313afd1462ea5f6',
    messagingSenderId: '902994248515',
    projectId: 'simple-app-c6c5a',
    authDomain: 'simple-app-c6c5a.firebaseapp.com',
    storageBucket: 'simple-app-c6c5a.appspot.com',
    measurementId: 'G-JBZNTK3GWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwfizHqXO1QRAHp3vkKBgc0HRzNMqGmU',
    appId: '1:902994248515:android:9b165897876ed1f02ea5f6',
    messagingSenderId: '902994248515',
    projectId: 'simple-app-c6c5a',
    storageBucket: 'simple-app-c6c5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn4dySZABqJESK93IWQeb_PpHyAoJzlj8',
    appId: '1:902994248515:ios:72d55453fef62bee2ea5f6',
    messagingSenderId: '902994248515',
    projectId: 'simple-app-c6c5a',
    storageBucket: 'simple-app-c6c5a.appspot.com',
    iosBundleId: 'com.example.simple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn4dySZABqJESK93IWQeb_PpHyAoJzlj8',
    appId: '1:902994248515:ios:72d55453fef62bee2ea5f6',
    messagingSenderId: '902994248515',
    projectId: 'simple-app-c6c5a',
    storageBucket: 'simple-app-c6c5a.appspot.com',
    iosBundleId: 'com.example.simple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_BcKXYXUevKyewJyCrWGiyaGlACdi-Ak',
    appId: '1:902994248515:web:12a52608542ebca22ea5f6',
    messagingSenderId: '902994248515',
    projectId: 'simple-app-c6c5a',
    authDomain: 'simple-app-c6c5a.firebaseapp.com',
    storageBucket: 'simple-app-c6c5a.appspot.com',
    measurementId: 'G-25ZJD14LDG',
  );
}
